projects:
  instagram:
    schemaPath: amplify/backend/api/instagram/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-north-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
